### ISSUE TITLE
Where is the code to authenticate and authorize users?

### ISSUE THREAD

**Issue by biapar** [umbraco/UmbracoRestApi#18]
Where is the code to authenticate and authorize users?

**Comment by Shazwazza** [comment]
Simple question that doesn't have a simple answer.

See: https://github.com/umbraco/UmbracoRestApi/issues/2

and then: https://github.com/umbraco/UmbracoRestApi/issues/17

The authorization is done by an attribute [UmbracoAuthorize], the authentication is done by either the token auth server built in to IdentityExtensions, or if you've enabled cookie authentication. https://our.umbraco.org/Documentation/Implementation/Rest-Api/
