### ISSUE TITLE
Member authentication

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoRestApi#2]
Just like user's we need to enable member auth. Currently however we are not implementing ASP.Net identity for Members in the core in Umbraco 7.3 since we have the UmbracoIdentity package for that currently. In the future this will be integrated in to 7.3 but we don't have time for that for this release. 

Until we look into authenticating members for the REST API, I'm not sure if we'll need to include the UmbracoIdentity package for that purpose or not yet.

Member authentication comes with it's own security implications.... meaning that will need to apply security policies and also custom security code (we have another task for this)

**Comment by moppa** [comment]
Is there a road map entry/issue for ASP.Net Members in Core? This is a highly anticipated feature :)!

**Comment by Shazwazza** [comment]
We have a lot of things to release before hand for the core. I realize this is a required feature but probably won't get any attention until late first quarter 2016.

**Comment by olosvik** [comment]
I am really looking forward to this extension allowing members to auth. Are there any news on the progression?

**Comment by Shazwazza** [comment]
Sorry haven't had time to prioritize this, have responded with some more details here though: https://github.com/umbraco/UmbracoRestApi/issues/17

**Comment by Shazwazza** [comment]
Moved to 

http://issues.umbraco.org/issue/U4-10319
http://issues.umbraco.org/issue/U4-10320
