### ISSUE TITLE
Published Content controller should not require any authorization - this is public just like the website

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoRestApi#23]

**Comment by perploug** [comment]
I would say that we should keep it behind auth - we would expose all content in the site - including hidden pages and "system" properties - for instance if a developer stored a private API key on a page - that would be exposed via the api

**Comment by Shazwazza** [comment]
but all pages are public if they are published ... they all have public URLs

I plan on implementing the authz to be done via policies so I suppose a developer can make this public if they want by policy

**Comment by Shazwazza** [comment]
ahh but i see what you mean... not all properties might be public, only what is seen on the template. Gotcha. Well we'll make it flexible :)

**Comment by perploug** [comment]
exactly :) - but giving devs the flexibility to change this via a policy would make fine sense - so in case they do want everything public they can do that - but not by default
