### ISSUE TITLE
How to authorize the relations controller?

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoRestApi#24]
What part of relations are public? Are all relations public (not really sure there's any security risk returning related IDs?) Of course if a relation is for a member, you'll just get an ID and then you'll need to request the member info from the members endpoint - for which you'd need to be authorized to get.

So ... should the relations controller just be public?

**Comment by perploug** [comment]
is anything in the rest api public? - imo it is all behind Auth  - if you mean who can see relations - then yeah everyone could see the IDs of the related items and the auth would kick on the individual controller

**Comment by Shazwazza** [comment]
Yup that's what i means. I'm changing the auth, but i guess with auth policies it will be up to the user to decide who has access to what.

The other part of the relation auth is that different users have access to different sections, etc... Currently that auth isn't enforced on the REST API but it will be, so for relations API, it will continue by default to just auth any authenticated user but if that user attempts to access member data (for example), they will need to have access to member data.

**Comment by perploug** [comment]
Sounds good - can we include that info in the error message? - so the user can tell that is why the call is failing - due to the user not having access to certain data - or is it simply the generic "not-allowed" response?

**Comment by Shazwazza** [comment]
adding that info to the response is a security no-no. It will simply give a 401 unauthorized response
