### ISSUE TITLE
Support for UDIs

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/UmbracoRestApi#27]

**Comment by perploug** [comment]
What would be the best way to go about this ? - make the ID parameter on endpoints a string and then simply detect if its a udi, int or guid? - and then act based on that

Also - is there a url handling issue with UDIs ? 

for instance called /rest/content/1234/children is fine - but is /rest/content/ [umb://content/guid/] /children 

I guess the UDI part would be url-encoded and not be an issue - just ugly

**Comment by Shazwazza** [comment]
That's exactly what i mentioned on Slack.... we will *not* have UDIs as part of the URL, 

> About the udi stuff, it's fine that we include the udi with the response but we don't query with a udi. We've tried this before in v5, having a uri encoded in a uri is horrible. A udi is just a guid with a schema so all we really need to do is send out the udi and guid in the response of each object and also support querying by guid

**Comment by Shazwazza** [comment]
PR is here: https://github.com/umbraco/UmbracoRestApi/pull/39
