### ISSUE TITLE
Unable to get single content item - returning 404s

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/UmbracoRestApi#6]
When using the HAL Browser to click around the Content API endpoint with the Faroe StarterKit installed.

I get 404's from the following API endpoints
/umbraco/rest/v1/content/1063
/umbraco/rest/v1/content/1063/meta
/umbraco/rest/v1/content/1063/children?pageIndex=5&pageSize=1
/umbraco/rest/v1/content/1063/descendants?pageIndex=1&pageSize=5
/umbraco/rest/v1/content/1063/upload

**Comment by Shazwazza** [comment]
gonna close this one, things are defo working so not sure what was going on before
