### ISSUE TITLE
Unable to find the requested .Net Framework Data Provider.  It may not be installed.

### ISSUE THREAD

**Issue by qz2rg4** [umbraco/UmbracoRestApi#8]
Hi I receive this error message after a clean install of u7.3.1 and UmbracoRestApi

Thanks for the help

**Comment by Shazwazza** [comment]
Can you provide some more detail please? Where do you see this message, etc... ?

**Comment by qz2rg4** [comment]
http://screencast.com/t/9EuDjxQQE1l

Thanks

**Comment by ryanmcdonough** [comment]
Is this still an issue? Looks like your site is up and running now.
