### ISSUE TITLE
Need ability to publishing content (not just save)

### ISSUE THREAD

**Issue by griff158** [umbraco/UmbracoRestApi#9]
Hi,

I'm testing UmbracoRestApi 0.9.0 together with Umbraco 7.3.1 and after some configuration i'm able to update a document i see the change in the backend, but the page is not updated. This seems to be related to the xml cache file which still had the old values in it. Do i need to make a publish call after the update (put) request?

**Comment by Shazwazza** [comment]
The source for the content controller is here: 

https://github.com/umbraco/UmbracoRestApi/blob/master/src/Umbraco.RestApi/Controllers/ContentController.cs

CreateNew and Update only manipulate the content in the database, there is currently no method/operation to publish content, this would need to be implemented as an additional method. The PublishedContent controller is for readonly operations against published content.

It would be fairly easy to include this functionality, I'll update this task accordingly.
